homepage_lightrider_objectloader:
    pattern:  /Lightrider/Objects/{scope}/{filename}
    defaults: { _controller: HomepageLightriderBundle:ObjectLoader:index }

homepage_lightrider_main:
    pattern:  /Lightrider/
    defaults: { _controller: HomepageLightriderBundle:Main:index }

