homepage_lightrider_objectloader:
    pattern:  /Lightrider/loadObject/
    defaults: { _controller: HomepageLightriderBundle:ObjectLoader:index }

homepage_lightrider_main:
    pattern:  /Lightrider/
    defaults: { _controller: HomepageLightriderBundle:Main:index }

