lightrider_objectloader:
    pattern:  /Objects/{scope}/{filename}
    defaults: { _controller: LightriderBundle:ObjectLoader:index }

lightrider_settings:
    pattern:  /Settings/
    defaults: { _controller: LightriderBundle:Settings:index }

lightrider_render_window:
    pattern:  /RenderWindow/
    defaults: { _controller: LightriderBundle:RenderWindow:index }
    
lightrider_preloader:
    pattern:  /
    defaults: { _controller: LightriderBundle:Preloader:index }
