lightrider_objectloader:
    pattern:  /Lightrider/Objects/{scope}/{filename}
    defaults: { _controller: LightriderBundle:ObjectLoader:index }

lightrider_settings:
    pattern:  /Lightrider/Settings/
    defaults: { _controller: LightriderBundle:Settings:index }

lightrider_render_window:
    pattern:  /Lightrider/RenderWindow/
    defaults: { _controller: LightriderBundle:RenderWindow:index }
    
lightrider_preloader:
    pattern:  /Lightrider/
    defaults: { _controller: LightriderBundle:Preloader:index }

